// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cities_base.sql

package db

import (
	"context"
)

const getCitiesByIDs = `-- name: GetCitiesByIDs :many
SELECT c.geoname_id, c.city, c.state_code, c.country_code,
       ctr.country AS country, c.population, c.latitude, c.longitude, c.timezone,
       to_char(c.updated_date, 'YYYY-MM-DD') AS last_update
FROM cities c
LEFT JOIN countries ctr ON ctr.country_code = c.country_code
WHERE c.geoname_id = ANY($1::bigint[])
ORDER BY c.geoname_id
`

type GetCitiesByIDsRow struct {
	GeonameID   int64
	City        string
	StateCode   *string
	CountryCode string
	Country     *string
	Population  *int64
	Latitude    *float64
	Longitude   *float64
	Timezone    *string
	LastUpdate  string
}

func (q *Queries) GetCitiesByIDs(ctx context.Context, geonameIds []int64) ([]GetCitiesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCitiesByIDs, geonameIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCitiesByIDsRow
	for rows.Next() {
		var i GetCitiesByIDsRow
		if err := rows.Scan(
			&i.GeonameID,
			&i.City,
			&i.StateCode,
			&i.CountryCode,
			&i.Country,
			&i.Population,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCity = `-- name: GetCity :one
SELECT c.geoname_id, c.city, c.state_code, c.country_code,
       ctr.country AS country, c.population, c.latitude, c.longitude, c.timezone,
       to_char(c.updated_date, 'YYYY-MM-DD') AS last_update
FROM cities c
LEFT JOIN countries ctr ON ctr.country_code = c.country_code
WHERE c.geoname_id = $1::bigint
`

type GetCityRow struct {
	GeonameID   int64
	City        string
	StateCode   *string
	CountryCode string
	Country     *string
	Population  *int64
	Latitude    *float64
	Longitude   *float64
	Timezone    *string
	LastUpdate  string
}

func (q *Queries) GetCity(ctx context.Context, geonameID int64) (GetCityRow, error) {
	row := q.db.QueryRow(ctx, getCity, geonameID)
	var i GetCityRow
	err := row.Scan(
		&i.GeonameID,
		&i.City,
		&i.StateCode,
		&i.CountryCode,
		&i.Country,
		&i.Population,
		&i.Latitude,
		&i.Longitude,
		&i.Timezone,
		&i.LastUpdate,
	)
	return i, err
}

const listCities = `-- name: ListCities :many
SELECT c.geoname_id, c.city, c.state_code, c.country_code,
       ctr.country AS country, c.population, c.latitude, c.longitude, c.timezone,
       to_char(c.updated_date, 'YYYY-MM-DD') AS last_update
FROM cities c
LEFT JOIN countries ctr ON ctr.country_code = c.country_code
WHERE (LOWER(c.country_code) = LOWER($1::text) OR $1::text = '')
ORDER BY c.geoname_id
`

type ListCitiesRow struct {
	GeonameID   int64
	City        string
	StateCode   *string
	CountryCode string
	Country     *string
	Population  *int64
	Latitude    *float64
	Longitude   *float64
	Timezone    *string
	LastUpdate  string
}

func (q *Queries) ListCities(ctx context.Context, countryCode string) ([]ListCitiesRow, error) {
	rows, err := q.db.Query(ctx, listCities, countryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCitiesRow
	for rows.Next() {
		var i ListCitiesRow
		if err := rows.Scan(
			&i.GeonameID,
			&i.City,
			&i.StateCode,
			&i.CountryCode,
			&i.Country,
			&i.Population,
			&i.Latitude,
			&i.Longitude,
			&i.Timezone,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
