// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries_legatum.sql

package db

import (
	"context"
)

const getLegatumCountryIndicesByCodes = `-- name: GetLegatumCountryIndicesByCodes :many
SELECT
    li.country_code,
    jsonb_object_agg(l.key, l.value) AS legatum_indices
FROM legatum_country_indices li
CROSS JOIN LATERAL (
    SELECT
        CASE li.pillar_name
            WHEN 'Safety and Security' THEN 'safety_and_security'
            WHEN 'Personal Freedom' THEN 'personal_freedom'
            WHEN 'Governance' THEN 'governance'
            WHEN 'Social Capital' THEN 'social_capital'
            WHEN 'Investment Environment' THEN 'investment_invironment'
            WHEN 'Enterprise Conditions' THEN 'enterprise_conditions'
            WHEN 'Infrastructure and Market Access' THEN 'infrastructure_and_market_access'
            WHEN 'Economic Quality' THEN 'economic_quality'
            WHEN 'Living Conditions' THEN 'living_conditions'
            WHEN 'Health' THEN 'health'
            WHEN 'Education' THEN 'education'
            WHEN 'Natural Environment' THEN 'natural_environment'
        END AS key,
        to_jsonb(li) - 'country_code' - 'pillar_name' AS value
) AS l
WHERE li.country_code = ANY($1::text[]) AND l.key IS NOT NULL
GROUP BY li.country_code
`

type GetLegatumCountryIndicesByCodesRow struct {
	CountryCode    string
	LegatumIndices []byte
}

// Converts Legatum pillar names into API field names and aggregates them into
// a single JSON object per country.
func (q *Queries) GetLegatumCountryIndicesByCodes(ctx context.Context, countryCodes []string) ([]GetLegatumCountryIndicesByCodesRow, error) {
	rows, err := q.db.Query(ctx, getLegatumCountryIndicesByCodes, countryCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegatumCountryIndicesByCodesRow
	for rows.Next() {
		var i GetLegatumCountryIndicesByCodesRow
		if err := rows.Scan(&i.CountryCode, &i.LegatumIndices); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
