// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries_base.sql

package db

import (
	"context"
)

const getCountriesByCodes = `-- name: GetCountriesByCodes :many
SELECT ctr.country_code, ctr.country, ctr.population, ctr.area, ctr.last_update::text AS last_update
FROM countries ctr
WHERE ctr.country_code = ANY($1::text[])
ORDER BY ctr.country_code
`

type GetCountriesByCodesRow struct {
	CountryCode string
	Country     string
	Population  *int64
	Area        *int64
	LastUpdate  string
}

func (q *Queries) GetCountriesByCodes(ctx context.Context, countryCodes []string) ([]GetCountriesByCodesRow, error) {
	rows, err := q.db.Query(ctx, getCountriesByCodes, countryCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCountriesByCodesRow
	for rows.Next() {
		var i GetCountriesByCodesRow
		if err := rows.Scan(
			&i.CountryCode,
			&i.Country,
			&i.Population,
			&i.Area,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountryDetailed = `-- name: GetCountryDetailed :one
SELECT
    ctr.country_code,
    ctr.country,
    ctr.population,
    ctr.area,
    ctr.last_update::text AS last_update,
    CASE
        WHEN $1::boolean THEN (
            SELECT jsonb_build_object(
                'cost_of_living', nic.cost_of_living,
                'rent', nic.rent,
                'cost_of_living_plus_rent', nic.cost_of_living_plus_rent,
                'groceries', nic.groceries,
                'restaurant_price', nic.restaurant_price,
                'local_purchasing_power', nic.local_purchasing_power,
                'quality_of_life', nic.quality_of_life,
                'property_price_to_income_ratio', nic.property_price_to_income_ratio,
                'traffic_commute_time', nic.traffic_commute_time,
                'climate', nic.climate,
                'safety', nic.safety,
                'health_care', nic.health_care,
                'pollution', nic.pollution,
                'avg_salary_usd', nic.avg_salary_usd,
                'last_update', to_char(nic.updated_date, 'YYYY-MM-DD')
            )
            FROM numbeo_country_indices nic
            WHERE nic.country_code = ctr.country_code
        )
        ELSE NULL
    END AS numbeo_indices,
    CASE
        WHEN $2::boolean THEN (
            SELECT jsonb_object_agg(l.key, l.value)
            FROM legatum_country_indices li
            CROSS JOIN LATERAL (
                SELECT
                    CASE li.pillar_name
                        WHEN 'Safety and Security' THEN 'safety_and_security'
                        WHEN 'Personal Freedom' THEN 'personal_freedom'
                        WHEN 'Governance' THEN 'governance'
                        WHEN 'Social Capital' THEN 'social_capital'
                        WHEN 'Investment Environment' THEN 'investment_invironment'
                        WHEN 'Enterprise Conditions' THEN 'enterprise_conditions'
                        WHEN 'Infrastructure and Market Access' THEN 'infrastructure_and_market_access'
                        WHEN 'Economic Quality' THEN 'economic_quality'
                        WHEN 'Living Conditions' THEN 'living_conditions'
                        WHEN 'Health' THEN 'health'
                        WHEN 'Education' THEN 'education'
                        WHEN 'Natural Environment' THEN 'natural_environment'
                    END AS key,
                    to_jsonb(li) - 'country_code' - 'pillar_name' AS value
            ) AS l
            WHERE li.country_code = ctr.country_code AND l.key IS NOT NULL
        )
        ELSE NULL
    END AS legatum_indices
FROM countries ctr
WHERE ctr.country_code = $3::text
`

type GetCountryDetailedParams struct {
	IncludeNumbeoIndices  bool
	IncludeLegatumIndices bool
	CountryCode           string
}

type GetCountryDetailedRow struct {
	CountryCode    string
	Country        string
	Population     *int64
	Area           *int64
	LastUpdate     string
	NumbeoIndices  interface{}
	LegatumIndices interface{}
}

// Detail endpoint query. Optional include blocks are guarded by boolean
// parameters so unrequested JSON payloads are not built.
func (q *Queries) GetCountryDetailed(ctx context.Context, arg GetCountryDetailedParams) (GetCountryDetailedRow, error) {
	row := q.db.QueryRow(ctx, getCountryDetailed, arg.IncludeNumbeoIndices, arg.IncludeLegatumIndices, arg.CountryCode)
	var i GetCountryDetailedRow
	err := row.Scan(
		&i.CountryCode,
		&i.Country,
		&i.Population,
		&i.Area,
		&i.LastUpdate,
		&i.NumbeoIndices,
		&i.LegatumIndices,
	)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT country_code, country, population, area, last_update::text AS last_update
FROM countries
ORDER BY country_code
`

type ListCountriesRow struct {
	CountryCode string
	Country     string
	Population  *int64
	Area        *int64
	LastUpdate  string
}

func (q *Queries) ListCountries(ctx context.Context) ([]ListCountriesRow, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCountriesRow
	for rows.Next() {
		var i ListCountriesRow
		if err := rows.Scan(
			&i.CountryCode,
			&i.Country,
			&i.Population,
			&i.Area,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
