// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries_base.sql

package db

import (
	"context"
)

const getCountriesByCodes = `-- name: GetCountriesByCodes :many
SELECT ctr.country_code, ctr.country, ctr.population, ctr.area, ctr.last_update::text AS last_update
FROM countries ctr
WHERE ctr.country_code = ANY($1::text[])
ORDER BY ctr.country_code
`

type GetCountriesByCodesRow struct {
	CountryCode string
	Country     string
	Population  *int64
	Area        *int64
	LastUpdate  string
}

func (q *Queries) GetCountriesByCodes(ctx context.Context, countryCodes []string) ([]GetCountriesByCodesRow, error) {
	rows, err := q.db.Query(ctx, getCountriesByCodes, countryCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCountriesByCodesRow
	for rows.Next() {
		var i GetCountriesByCodesRow
		if err := rows.Scan(
			&i.CountryCode,
			&i.Country,
			&i.Population,
			&i.Area,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountry = `-- name: GetCountry :one
SELECT ctr.country_code, ctr.country, ctr.population, ctr.area, ctr.last_update::text AS last_update
FROM countries ctr
WHERE ctr.country_code = $1::text
`

type GetCountryRow struct {
	CountryCode string
	Country     string
	Population  *int64
	Area        *int64
	LastUpdate  string
}

func (q *Queries) GetCountry(ctx context.Context, countryCode string) (GetCountryRow, error) {
	row := q.db.QueryRow(ctx, getCountry, countryCode)
	var i GetCountryRow
	err := row.Scan(
		&i.CountryCode,
		&i.Country,
		&i.Population,
		&i.Area,
		&i.LastUpdate,
	)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT country_code, country, population, area, last_update::text AS last_update
FROM countries
ORDER BY country_code
`

type ListCountriesRow struct {
	CountryCode string
	Country     string
	Population  *int64
	Area        *int64
	LastUpdate  string
}

func (q *Queries) ListCountries(ctx context.Context) ([]ListCountriesRow, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCountriesRow
	for rows.Next() {
		var i ListCountriesRow
		if err := rows.Scan(
			&i.CountryCode,
			&i.Country,
			&i.Population,
			&i.Area,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
