// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AvgClimate struct {
	GeonameID    int64
	Month        int16
	HighTemp     pgtype.Numeric
	LowTemp      pgtype.Numeric
	Pressure     pgtype.Numeric
	WindSpeed    pgtype.Numeric
	Humidity     pgtype.Numeric
	Rainfall     pgtype.Numeric
	RainfallDays pgtype.Numeric
	Snowfall     pgtype.Numeric
	SnowfallDays pgtype.Numeric
	SeaTemp      pgtype.Numeric
	Daylight     pgtype.Numeric
	Sunshine     pgtype.Numeric
	SunshineDays pgtype.Numeric
	UvIndex      pgtype.Numeric
	CloudCover   pgtype.Numeric
	Visibility   pgtype.Numeric
	UpdatedDate  pgtype.Date
	UpdatedBy    *string
}

type City struct {
	GeonameID   int64
	City        string
	StateCode   *string
	CountryCode string
	Population  *int64
	Latitude    *float64
	Longitude   *float64
	Timezone    *string
	UpdatedDate pgtype.Date
	UpdatedBy   *string
}

type Country struct {
	Country     string
	Alpha2Code  *string
	CountryCode string
	NumericCode *int64
	Independent *string
	Population  *int64
	Area        *int64
	LastUpdate  pgtype.Date
}

type LegatumCountryIndex struct {
	CountryCode string
	AreaGroup   *string
	PillarName  string
	Rank2007    *int64
	Rank2008    *int64
	Rank2009    *int64
	Rank2010    *int64
	Rank2011    *int64
	Rank2012    *int64
	Rank2013    *int64
	Rank2014    *int64
	Rank2015    *int64
	Rank2016    *int64
	Rank2017    *int64
	Rank2018    *int64
	Rank2019    *int64
	Rank2020    *int64
	Rank2021    *int64
	Rank2022    *int64
	Rank2023    *int64
	Score2007   *float64
	Score2008   *float64
	Score2009   *float64
	Score2010   *float64
	Score2011   *float64
	Score2012   *float64
	Score2013   *float64
	Score2014   *float64
	Score2015   *float64
	Score2016   *float64
	Score2017   *float64
	Score2018   *float64
	Score2019   *float64
	Score2020   *float64
	Score2021   *float64
	Score2022   *float64
	Score2023   *float64
}

type NumbeoCityCost struct {
	GeonameID   int64
	ParamID     int32
	Cost        pgtype.Numeric
	Range       pgtype.Range[pgtype.Numeric]
	LastUpdate  pgtype.Date
	UpdatedDate pgtype.Date
	UpdatedBy   *string
}

type NumbeoCityIndex struct {
	GeonameID                  int64
	CostOfLiving               *float64
	Rent                       *float64
	CostOfLivingPlusRent       *float64
	Groceries                  *float64
	LocalPurchasingPower       *float64
	QualityOfLife              *float64
	PropertyPriceToIncomeRatio *float64
	TrafficCommuteTime         *float64
	Climate                    *float64
	Safety                     *float64
	HealthCare                 *float64
	Pollution                  *float64
	UpdatedDate                pgtype.Date
	UpdatedBy                  *string
}

type NumbeoCostCategory struct {
	CategoryID int32
	Category   string
}

type NumbeoCostParam struct {
	ParamID    int32
	CategoryID int32
	Param      string
}

type NumbeoCountryIndex struct {
	CountryCode                string
	CostOfLiving               *float64
	Rent                       *float64
	CostOfLivingPlusRent       *float64
	Groceries                  *float64
	RestaurantPrice            *float64
	LocalPurchasingPower       *float64
	QualityOfLife              *float64
	PurchasingPower            *float64
	HealthCare                 *float64
	PropertyPriceToIncomeRatio *float64
	TrafficCommuteTime         *float64
	Pollution                  *float64
	Climate                    *float64
	AvgSalaryUsd               *float64
	Safety                     *float64
	UpdatedDate                pgtype.Date
	UpdatedBy                  *string
}

type State struct {
	StateCode string
	StateName string
	Category  *string
}

type Token struct {
	Hash   []byte
	UserID int64
	Expiry pgtype.Timestamptz
	Scope  string
}

type User struct {
	ID           int64
	CreatedAt    pgtype.Timestamptz
	Name         string
	Email        string
	PasswordHash []byte
	Activated    bool
	Version      int32
}
